runtime: php
env: flex

runtime_config:
  document_root: public

# required on some platforms so ".env" is not skipped
skip_files: false

env_variables:
  # The values here will override those in ".env". This is useful for
  # production-specific configuration. However, feel free to set these
  # values in ".env" instead if you prefer.
  APP_LOG: errorlog
  APP_ENV: production
  STORAGE_DIR: /tmp
  GOOGLE_REDIRECT: http://awakin.aici.me/callback
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  # CloudSQL configuration
  DB_CONNECTION:  mysql
  DB_HOST: localhost
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_SOCKET: /cloudsql/awakin-162908:europe-west1:awakin1
  
beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "awakin-162908:europe-west1:awakin1"
    
manual_scaling:
  instances: 1